### ISSUE TITLE
Incorrect definition for @typescript-eslint/consistent-type-assertions

### ISSUE THREAD

**Issue by Tatsh** [fox-projects/jsonschema-extractor#4]
https://github.com/fox-projects/jsonschema-extractor/blob/b5819454ef1206255e3107215b36418b7b4c85a9/schemas/partial-eslint.schema.json#L9679-L9711

[consistent-type-assertions](https://typescript-eslint.io/rules/consistent-type-assertions#options) says that options `assertionStyle` and `objectLiteralAssertions` are available.

Simplest way to fix would be to set `additionalProperties` to `true`.

Then https://github.com/SchemaStore/schemastore needs to be updated.

**Comment by hyperupcall** [comment]
Thanks for the report! Fixed by 648bbeb51fdb459c193acdc7756d5f79e1b3865a (updated dependencies (which has the proper schema for the plugin), and set `additionalProperties` to `true` for all subschemas)
